# .goreleaser.yml
# Build customization

builds:
  - binary: zeus
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    hooks:
      pre: rice embed-go

brews:
  -
    # Repository to push the tap to.
    tap:
      owner: dreadl0ck
      name: homebrew-formulas

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    #folder: Formulas

    # Your app's homepage
    # Default is empty
    homepage: "https://github.com/dreadl0ck/zeus"

    # Your app's description
    # Default is empty
    description: "An Electrifying Build System"