# Makefile for automated migration test

GLOBALVAR="TEST"

all: clean configure
	# some comment
	go build

clean:
	# some comment
	cleanup

build:
	# some comment
	go build

	# some comment
	more build

# comment
configure:
	configure